DATASET:
    NAME: "glass_with_fakemix"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    PATH: 'datasets/glass_detection'
TRAIN:
    EPOCHS: 200
    BATCH_SIZE: 6
    CROP_SIZE: 769
    BASE_SIZE: 416
    MODEL_SAVE_DIR: 'workdirs/other_datasets/gdd'
    BLOSS_WEIGHT: 1.0   
TEST:
    BATCH_SIZE: 1
    TEST_MODEL_PATH: 'workdirs/other_datasets/gdd/gdd_compared_with_gdnet.pth'

SOLVER:
    LR: 0.01
    STEP:
        DECAY_EPOCH: [30, 60]

MODEL:
    MODEL_NAME: "FANet"
    BACKBONE: "gluon_resnext101_32x4d"
