DATASET:
    NAME: "trans10k_with_fakemix"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 400
    BATCH_SIZE: 4
    CROP_SIZE: 769
    MODEL_SAVE_DIR: 'workdirs/trans10k'
    BLOSS_WEIGHT: 1.0  
    FAKE_BOUNDARY_COUNT: 3 
TEST:
    BATCH_SIZE: 1
    TEST_MODEL_PATH: 'workdirs/trans10k/400.pth'

SOLVER:
    LR: 0.01
    STEP:
        DECAY_EPOCH: [30, 60]

MODEL:
    MODEL_NAME: "FANet"
    BACKBONE: "resnet50"

